"use client";
import Link from "next/link";
import { useActionState } from "react";
import { analyzeAirbnbAction, confirmAirbnbImportAction, type AirbnbAnalysisState, type AirbnbConfirmationState } from "@/lib/airbnb/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";

export function AirbnbImportForm({ owners }: { owners: Array<{ id: string; label: string }> }) {
  const [analysis, analyze, analyzing] = useActionState(analyzeAirbnbAction, {} as AirbnbAnalysisState);
  const [confirmation, confirm, confirming] = useActionState(confirmAirbnbImportAction, {} as AirbnbConfirmationState);
  const preview = analysis.preview;
  if (confirmation.apartmentId) return <Card className="p-6"><h2 className="text-xl font-semibold">Import terminé</h2><p className="mt-2 text-sm text-muted-foreground">L’appartement est enregistré en brouillon.</p><Button asChild className="mt-4"><Link href={`/dashboard/apartments/${confirmation.apartmentId}`}>Vérifier la fiche</Link></Button></Card>;
  return <div className="space-y-6"><Card className="p-6"><form action={analyze} className="space-y-4"><label className="block text-sm font-medium">URL de l’annonce Airbnb<Input name="url" type="url" required defaultValue="https://fr.airbnb.com/rooms/1691872650571602529" className="mt-2" /></label><Button disabled={analyzing}>{analyzing ? "Analyse en cours…" : "Analyser l’annonce"}</Button>{analyzing && <p role="status" className="text-sm text-muted-foreground">Ouverture · Extraction · Équipements · Photos · Aperçu</p>}{analysis.error && <p role="alert" className="text-sm text-ruby">{analysis.error}</p>}</form></Card>
  {preview && <form action={confirm} className="space-y-6"><input type="hidden" name="extraction" value={JSON.stringify(preview.extraction)} /><input type="hidden" name="contentHash" value={preview.contentHash} />
    <Card className="p-6"><p className="text-xs uppercase tracking-wider text-gold">Aperçu avant import</p><h2 className="mt-1 text-2xl font-semibold">{preview.extraction.identity.title ?? "Titre à compléter"}</h2><p className="text-sm text-muted-foreground">Airbnb #{preview.extraction.source.listingId} · {preview.extraction.photos.length} photos · {preview.extraction.amenities.available.length} équipements · {preview.extraction.missingFields.length} champs manquants</p><div className="mt-5 grid gap-3 sm:grid-cols-4">{[["Voyageurs",preview.extraction.capacity.maxGuests],["Chambres",preview.extraction.capacity.bedrooms],["Lits",preview.extraction.capacity.beds],["Salles de bain",preview.extraction.capacity.bathrooms]].map(([label,value]) => <div key={String(label)} className="rounded-sm border border-border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{value ?? "À confirmer"}</p></div>)}</div></Card>
    <Card className="space-y-4 p-6"><h3 className="text-lg font-semibold">Valeurs à confirmer</h3><div className="grid gap-4 sm:grid-cols-2"><Field label="Titre"><Input name="title" required defaultValue={preview.extraction.identity.title ?? ""} /></Field><Field label="Ville"><Input name="city" required defaultValue={preview.extraction.location.city ?? "Marrakech"} /></Field><Field label="Type"><Select name="propertyType" defaultValue={preview.mappedPropertyType} values={["apartment","studio","villa","riad","house","private_room","penthouse","other"]} /></Field><Field label="Propriétaire"><select name="ownerId" required defaultValue="" className="h-10 w-full rounded-sm border border-border bg-surface px-3"><option value="" disabled>Sélectionner</option>{owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.label}</option>)}</select></Field><Field label="Tarif Yakout facultatif"><Input name="pricePerNight" type="number" min="1" /></Field><Field label="Devise"><Input name="currency" defaultValue="MAD" maxLength={3} /></Field></div><Field label="Description courte"><textarea name="shortDescription" maxLength={220} defaultValue={preview.generatedShortDescription} className="min-h-24 w-full rounded-sm border border-border bg-surface p-3" /></Field><Field label="Mode"><Select name="mode" defaultValue="create" values={["create","fill_empty","selective_update"]} /></Field></Card>
    <Card className="p-6"><h3 className="text-lg font-semibold">Photos candidates</h3><p className="mt-1 text-sm text-muted-foreground">Les six premières photos sont présélectionnées. Formats acceptés : JPEG, PNG, WebP et AVIF.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{preview.extraction.photos.slice(0,6).map((photo) => <label key={photo.sourceUrl} className="overflow-hidden rounded-sm border border-border bg-card text-sm"><span className="block aspect-[4/3] bg-cover bg-center" style={{ backgroundImage: `url(${JSON.stringify(photo.highResolutionUrl)})` }} /><span className="flex gap-2 p-3"><input type="checkbox" name="photos" value={photo.highResolutionUrl} defaultChecked />Photo {photo.order + 1}</span></label>)}</div><p className="mt-3 text-xs text-muted-foreground">{Math.min(preview.extraction.photos.length, 6)} photo(s) sélectionnable(s) sur {preview.extraction.photos.length} détectée(s).</p><label className="mt-5 flex gap-2 text-sm"><input type="checkbox" name="imageRightsConfirmed" required />Je confirme les droits de réutilisation des photos.</label></Card>
    {confirmation.error && <p role="alert" className="text-sm text-ruby">{confirmation.error}</p>}<Button disabled={confirming}>{confirming ? "Import en cours…" : "Confirmer l’import en brouillon"}</Button></form>}</div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-2 text-sm font-medium"><span>{label}</span>{children}</label>; }
function Select({ name, defaultValue, values }: { name: string; defaultValue: string; values: string[] }) { return <select name={name} defaultValue={defaultValue} className="h-10 w-full rounded-sm border border-border bg-surface px-3">{values.map((value) => <option key={value} value={value}>{value}</option>)}</select>; }
