"use client";

import Link from "next/link";
import { useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, Expand, RefreshCw, Search, X } from "lucide-react";
import type { CalendarApartment, CalendarBlock, ReservationCalendarEvent } from "@/lib/calendar/reservation-calendar";

type View = "planning" | "month" | "agenda" | "occupancy";
type Props = { view: View; from: string; to: string; today: string; reservations: ReservationCalendarEvent[]; apartments: CalendarApartment[]; blocks: CalendarBlock[]; warnings: Array<{code:string;message:string}>; loadedAt: string; search?: string };
const dayMs = 86_400_000;
const statusLabels = { option:"Option", confirmed:"Confirmée", checked_in:"En séjour", checked_out:"Terminée", cancelled:"Annulée", other:"Autre" } as const;
const paymentLabels = { paid:"Payé", partial:"Partiellement payé", unpaid:"Non payé", overpaid:"Trop-perçu", refunded:"Remboursé", unknown:"Données indisponibles" } as const;
const statusClass = { option:"border-amber-500 bg-amber-500/15 text-amber-950 dark:text-amber-100", confirmed:"border-ruby bg-ruby/15 text-foreground", checked_in:"border-emerald-600 bg-emerald-500/15 text-emerald-950 dark:text-emerald-100", checked_out:"border-slate-500 bg-slate-500/15 text-foreground", cancelled:"border-red-400 bg-red-500/10 text-muted-foreground line-through", other:"border-border bg-muted text-foreground" } as const;

function dateMs(value:string){const [y,m,d]=value.split("-").map(Number);return Date.UTC(y,m-1,d)}
function iso(ms:number){const d=new Date(ms);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`}
function dates(from:string,to:string){const values:string[]=[];for(let ms=dateMs(from);ms<dateMs(to);ms+=dayMs) values.push(iso(ms));return values}
function fr(value:string,short=false){const [y,m,d]=value.split("-");return short?`${d}/${m}`:`${d}/${m}/${y}`}
function shift(value:string,amount:number){return iso(dateMs(value)+amount*dayMs)}
function money(value:number|null,currency="MAD"){return value==null?"Indisponible":`${value.toLocaleString("fr-FR")} ${currency}`}
function url(view:View,from:string,to:string,extra=""){return `/dashboard/reservations/calendar?view=${view}&from=${from}&to=${to}${extra}`}

export function ReservationCalendarCockpit(props:Props){
  const [fullscreen,setFullscreen]=useState(false); const [selected,setSelected]=useState<ReservationCalendarEvent|null>(null);
  const days=dates(props.from,props.to); const today=props.today; const step=Math.max(1,days.length);
  const arrivals=props.reservations.filter(r=>r.checkIn===today); const departures=props.reservations.filter(r=>r.checkOut===today);
  const inStay=props.reservations.filter(r=>r.checkIn<=today&&r.checkOut>today&&r.reservationStatus!=="cancelled");
  const unavailableIds=new Set([
    ...inStay.map(r=>r.apartmentId).filter((id): id is string=>Boolean(id)),
    ...props.blocks.filter(block=>block.date===today).map(block=>block.apartmentId).filter((id): id is string=>Boolean(id)),
  ]); const available=Math.max(0,props.apartments.length-unavailableIds.size);
  const options=props.reservations.filter(r=>r.reservationStatus==="option"); const unpaid=props.reservations.filter(r=>r.paymentStatus==="partial"||r.paymentStatus==="unpaid"); const conflicts=props.reservations.filter(r=>r.isConflict);
  const kpis=[['Arrivées',arrivals.length,'Séjours commençant aujourd’hui'],['Départs',departures.length,'Séjours se terminant aujourd’hui'],['En séjour',inStay.length,'Séjours actifs dans l’intervalle arrivée incluse, départ exclu'],['Disponibles',available,'Appartements sans séjour actif aujourd’hui'],['Options',options.length,'Demandes en option ou pré-réservation'],['À régulariser',unpaid.length,'Paiements partiels ou non payés'],['Conflits',conflicts.length,'Chevauchements bloquants sur un même appartement']] as const;
  const prevFrom=shift(props.from,-step),prevTo=shift(props.to,-step),nextFrom=shift(props.from,step),nextTo=shift(props.to,step);
  return <div className={fullscreen?"fixed inset-0 z-[100] overflow-auto bg-background p-4":"space-y-5"}>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Réservations / Pilotage opérationnel</p><h1 className="mt-1 font-display text-3xl font-semibold">Calendrier des séjours</h1><p className="mt-1 text-sm text-muted-foreground">Du {fr(props.from)} au {fr(shift(props.to,-1))} · Mise à jour {new Date(props.loadedAt).toLocaleString("fr-FR",{timeZone:"Africa/Casablanca"})}</p></div><div className="flex flex-wrap gap-2"><Link className="tool" href={url(props.view,today,shift(today,14))}>Aujourd’hui</Link><Link aria-label="Période précédente" className="tool" href={url(props.view,prevFrom,prevTo)}><ArrowLeft className="size-4"/></Link><Link aria-label="Période suivante" className="tool" href={url(props.view,nextFrom,nextTo)}><ArrowRight className="size-4"/></Link><button className="tool" onClick={()=>setFullscreen(v=>!v)}><Expand className="size-4"/>{fullscreen?"Quitter":"Plein écran"}</button><Link aria-label="Actualiser" className="tool" href={url(props.view,props.from,props.to)}><RefreshCw className="size-4"/></Link></div></div>
    {props.warnings.map(w=><div key={w.code} className="flex gap-2 rounded-sm border border-amber-500/40 bg-amber-500/10 p-3 text-sm"><AlertTriangle className="size-4 shrink-0"/>{w.message}</div>)}
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-7">{kpis.map(([label,value,tip])=><button key={label} title={tip} className={`min-h-20 rounded-sm border bg-card p-3 text-left shadow-elevation-1 ${label==='Conflits'&&value?'border-red-500':'border-border'}`}><span className="text-xs text-muted-foreground">{label}</span><strong className="mt-1 block text-2xl tabular-nums">{value}</strong></button>)}</div>
    <div className="flex flex-col gap-3 rounded-sm border border-border bg-card p-3 xl:flex-row xl:items-center xl:justify-between"><nav aria-label="Modes du calendrier" className="flex overflow-x-auto">{([['planning','Planning'],['month','Mois'],['agenda','Agenda'],['occupancy','Occupation']] as [View,string][]).map(([value,label])=><Link key={value} href={url(value,props.from,props.to)} className={`min-h-11 whitespace-nowrap border-b-2 px-4 py-3 text-sm ${props.view===value?'border-gold font-semibold text-gold':'border-transparent text-muted-foreground'}`}>{label}</Link>)}</nav><form className="flex flex-wrap gap-2"><input type="hidden" name="view" value={props.view}/><input type="hidden" name="from" value={props.from}/><input type="hidden" name="to" value={props.to}/><label className="relative min-w-56 flex-1"><span className="sr-only">Rechercher</span><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input name="search" defaultValue={props.search} placeholder="Réservation, voyageur, appartement" className="min-h-11 w-full rounded-sm border border-border bg-background pl-9 pr-3 text-sm"/></label><button className="tool" type="submit">Filtrer</button>{props.search&&<Link className="tool" href={url(props.view,props.from,props.to)}>Réinitialiser</Link>}</form></div>
    <Legend/>
    {props.view==="planning"&&<><div className="md:hidden"><Agenda reservations={props.reservations} blocks={props.blocks} days={days.slice(0,7)} onSelect={setSelected}/></div><div className="hidden md:block"><Planning {...props} days={days} today={today} onSelect={setSelected}/></div></>}
    {props.view==="month"&&<Month reservations={props.reservations} blocks={props.blocks} apartments={props.apartments} days={days} onSelect={setSelected}/>} {props.view==="agenda"&&<Agenda reservations={props.reservations} blocks={props.blocks} days={days.slice(0,14)} onSelect={setSelected}/>} {props.view==="occupancy"&&<Occupancy reservations={props.reservations} apartments={props.apartments} blocks={props.blocks} days={days}/>} 
    {selected&&<ReservationPanel event={selected} onClose={()=>setSelected(null)}/>}<style jsx global>{`.tool{display:inline-flex;min-height:44px;align-items:center;justify-content:center;gap:.4rem;border:1px solid hsl(var(--border));border-radius:.25rem;padding:.55rem .8rem;font-size:.8rem;background:hsl(var(--card));}.tool:focus-visible{outline:2px solid hsl(var(--ring));outline-offset:2px}`}</style>
  </div>
}

function Legend(){return <div className="flex flex-wrap gap-x-5 gap-y-2 rounded-sm border border-border bg-card px-4 py-3 text-xs" aria-label="Légende"><strong>Réservations</strong>{Object.entries(statusLabels).slice(0,5).map(([k,v])=><span key={k} className="flex items-center gap-1.5"><i className={`size-3 rounded-sm border ${statusClass[k as keyof typeof statusClass]}`}/>{v}</span>)}<strong>Opérations</strong><span>◆ Maintenance</span><span className="text-red-600">⚠ Conflit</span><strong>Paiements</strong><span>● Payé</span><span>◐ Partiel</span><span>○ Non payé</span><span>? Indisponible</span></div>}

function Planning({reservations,apartments,blocks,days,today,onSelect}:{reservations:ReservationCalendarEvent[];apartments:CalendarApartment[];blocks:CalendarBlock[];days:string[];today:string;onSelect:(e:ReservationCalendarEvent)=>void}){
  const unassigned=reservations.filter(r=>!r.apartmentId); return <div className="overflow-auto rounded-sm border border-border bg-card" data-testid="planning-scroll"><div style={{minWidth:280+days.length*96}}><div className="sticky top-0 z-30 grid bg-card" style={{gridTemplateColumns:`280px repeat(${days.length},96px)`}}><div className="sticky left-0 z-40 border-b border-r border-border bg-card p-3 font-semibold">Appartement</div>{days.map(day=><div key={day} className={`border-b border-r border-border p-2 text-center text-xs ${day===today?'bg-gold/20 font-bold text-gold':new Date(dateMs(day)).getUTCDay()%6===0?'bg-muted/50':''}`}>{fr(day,true)}{day===today&&<span className="block">Aujourd’hui</span>}</div>)}</div>{apartments.map(apt=><ApartmentRow key={apt.id} apartment={apt} days={days} reservations={reservations.filter(r=>r.apartmentId===apt.id)} blocks={blocks.filter(b=>b.apartmentId===apt.id)} onSelect={onSelect}/>)}{unassigned.length>0&&<ApartmentRow apartment={{id:'unassigned',title:'Non affectées',district:null,capacity:0,imageUrl:null,operationalStatus:'Attention'}} days={days} reservations={unassigned} blocks={[]} onSelect={onSelect}/>}</div></div>}
function ApartmentRow({apartment,days,reservations,blocks,onSelect}:{apartment:CalendarApartment;days:string[];reservations:ReservationCalendarEvent[];blocks:CalendarBlock[];onSelect:(e:ReservationCalendarEvent)=>void}){const occupied=new Set(days.filter(day=>reservations.some(r=>r.reservationStatus!=="cancelled"&&r.checkIn<=day&&r.checkOut>day))).size;const rate=days.length?Math.round(occupied/days.length*100):0;return <div className="relative grid min-h-24" style={{gridTemplateColumns:`280px repeat(${days.length},96px)`}}><Link href={apartment.id==='unassigned'?'/dashboard/reservations?unassigned=1':`/dashboard/apartments/${apartment.id}`} className="sticky left-0 z-20 border-b border-r border-border bg-card p-3 hover:bg-muted"><strong className="block truncate text-sm">{apartment.title}</strong><span className="mt-1 block text-xs text-muted-foreground">{apartment.district??'Quartier non renseigné'}{apartment.capacity?` · ${apartment.capacity} pers.`:''}</span><span className="mt-2 block text-xs">Occupation : {rate} %</span></Link>{days.map(day=><div key={day} className="border-b border-r border-border/70 bg-background/40"/>)}<div className="pointer-events-none absolute inset-y-2 left-[280px] right-0 grid" style={{gridTemplateColumns:`repeat(${days.length},96px)`}}>{reservations.map(event=>{const start=Math.max(0,Math.round((dateMs(event.checkIn)-dateMs(days[0]))/dayMs));const end=Math.min(days.length,Math.round((dateMs(event.checkOut)-dateMs(days[0]))/dayMs));if(end<=0||start>=days.length)return null;return <button key={event.id} onClick={()=>onSelect(event)} aria-label={`Réservation ${event.reservationNumber}, ${event.apartmentTitle}, du ${fr(event.checkIn)} au ${fr(event.checkOut)}, ${statusLabels[event.reservationStatus].toLowerCase()}.`} className={`pointer-events-auto z-10 mx-1 self-center overflow-hidden rounded-sm border-l-4 px-2 py-2 text-left text-xs shadow-sm focus-visible:outline-2 focus-visible:outline-gold ${statusClass[event.reservationStatus]} ${event.isConflict?'ring-2 ring-red-600':''}`} style={{gridColumn:`${start+1} / span ${Math.max(1,end-start)}`}}><strong className="block truncate">{event.isConflict?'⚠ ':''}{event.reservationNumber} · {event.guestName}</strong><span className="block truncate">{event.guests} voy. · {event.balanceDue&&event.balanceDue>0?`${money(event.balanceDue)} restant`:paymentLabels[event.paymentStatus]}</span></button>})}{blocks.map(block=>{const start=Math.round((dateMs(block.date)-dateMs(days[0]))/dayMs);if(start<0||start>=days.length)return null;return <div key={block.id} title={block.title} className="z-10 m-1 self-end rounded-sm border border-violet-600 bg-violet-500/20 p-1 text-xs" style={{gridColumn:start+1}}>◆ {block.title}</div>})}</div></div>}

function Agenda({reservations,blocks,days,onSelect}:{reservations:ReservationCalendarEvent[];blocks:CalendarBlock[];days:string[];onSelect:(e:ReservationCalendarEvent)=>void}){return <div className="space-y-4">{days.map(day=>{const arrivals=reservations.filter(r=>r.checkIn===day),departures=reservations.filter(r=>r.checkOut===day),stays=reservations.filter(r=>r.checkIn<day&&r.checkOut>day&&r.reservationStatus!=="cancelled"),maintenance=blocks.filter(b=>b.date===day);if(!arrivals.length&&!departures.length&&!stays.length&&!maintenance.length)return null;return <section key={day} className="rounded-sm border border-border bg-card p-4"><h2 className="font-display text-lg font-semibold">{new Date(dateMs(day)).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'})}</h2>{[["Arrivées",arrivals],["Départs",departures],["En séjour",stays]] .map(([label,items])=><div key={label as string} className="mt-4"><h3 className="text-xs font-bold uppercase tracking-wider text-gold">{label as string}</h3><div className="mt-2 grid gap-2">{(items as ReservationCalendarEvent[]).map(e=><EventCard key={`${label}-${e.id}`} event={e} onSelect={onSelect}/>)}</div></div>)}{maintenance.length>0&&<div className="mt-4"><h3 className="text-xs font-bold uppercase tracking-wider text-violet-600">Interventions</h3>{maintenance.map(b=><p key={b.id} className="mt-2 rounded-sm border border-violet-500/40 p-3 text-sm">◆ {b.title} · {b.priority}</p>)}</div>}</section>})}<Empty show={!reservations.length&&!blocks.length} text="Aucune réservation sur cette période."/></div>}
function EventCard({event,onSelect}:{event:ReservationCalendarEvent;onSelect:(e:ReservationCalendarEvent)=>void}){return <button onClick={()=>onSelect(event)} className={`min-h-16 rounded-sm border-l-4 p-3 text-left ${statusClass[event.reservationStatus]}`}><strong>{event.isConflict?'⚠ ':''}{event.reservationNumber} · {event.apartmentTitle}</strong><span className="mt-1 block text-sm">{event.guestName} · {event.guests} voyageur{event.guests>1?'s':''} · {statusLabels[event.reservationStatus]}</span>{event.balanceDue!=null&&event.balanceDue>0&&<span className="block text-xs">Solde : {money(event.balanceDue)}</span>}</button>}

function Month({reservations,blocks,apartments,days,onSelect}:{reservations:ReservationCalendarEvent[];blocks:CalendarBlock[];apartments:CalendarApartment[];days:string[];onSelect:(e:ReservationCalendarEvent)=>void}){return <div className="grid grid-cols-1 gap-px overflow-hidden rounded-sm border border-border bg-border sm:grid-cols-2 lg:grid-cols-7">{days.map(day=>{const arr=reservations.filter(r=>r.checkIn===day),dep=reservations.filter(r=>r.checkOut===day),stay=reservations.filter(r=>r.checkIn<=day&&r.checkOut>day&&r.reservationStatus!=="cancelled"),maint=blocks.filter(b=>b.date===day),unavailable=new Set([...stay.map(r=>r.apartmentId),...maint.map(b=>b.apartmentId)].filter(Boolean));return <section key={day} className="min-h-36 bg-card p-3"><h2 className="font-semibold">{fr(day,true)}</h2><p className="mt-1 text-xs text-muted-foreground">{arr.length} arrivée · {dep.length} départ · {stay.length} en séjour</p><p className="text-xs text-muted-foreground">{Math.max(0,apartments.length-unavailable.size)} disponibles</p><div className="mt-2 space-y-1">{[...arr,...stay.filter(r=>!arr.includes(r))].slice(0,3).map(e=><button key={e.id} onClick={()=>onSelect(e)} className="block w-full truncate rounded-sm bg-muted px-2 py-1 text-left text-xs">{e.apartmentTitle} · {e.guestName}</button>)}{arr.length+stay.length>3&&<span className="text-xs text-gold">+ {arr.length+stay.length-3} autres</span>}{maint.map(b=><span key={b.id} className="block truncate text-xs text-violet-600">◆ {b.title}</span>)}</div></section>})}</div>}

function Occupancy({reservations,apartments,blocks,days}:{reservations:ReservationCalendarEvent[];apartments:CalendarApartment[];blocks:CalendarBlock[];days:string[]}){const active=reservations.filter(r=>r.reservationStatus!=="cancelled"),availableNights=apartments.length*days.length,occupiedNights=active.reduce((sum,r)=>sum+days.filter(d=>r.checkIn<=d&&r.checkOut>d).length,0),blocked=blocks.length,rate=availableNights?Math.round(occupiedNights/availableNights*100):0;const rows=apartments.map(a=>{const n=active.filter(r=>r.apartmentId===a.id).reduce((s,r)=>s+days.filter(d=>r.checkIn<=d&&r.checkOut>d).length,0);return {...a,n,rate:days.length?Math.round(n/days.length*100):0}}).sort((a,b)=>b.rate-a.rate);return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-4">{[['Occupation',`${rate} %`],['Nuits occupées',occupiedNights],['Nuits disponibles',Math.max(0,availableNights-occupiedNights-blocked)],['Nuits maintenance',blocked]].map(([l,v])=><div key={l} className="rounded-sm border border-border bg-card p-4"><span className="text-xs text-muted-foreground">{l}</span><strong className="mt-1 block text-2xl tabular-nums">{v}</strong></div>)}</div><div className="rounded-sm border border-border bg-card"><div className="border-b border-border p-4"><h2 className="font-semibold">Occupation par appartement</h2><p className="text-xs text-muted-foreground">Base : nuits réservées sur {days.length} jours visibles. Les encaissements ne sont pas affichés faute de source certifiée.</p></div>{rows.map(a=><Link href={`/dashboard/apartments/${a.id}`} key={a.id} className="grid grid-cols-[1fr_auto] gap-4 border-b border-border p-4 last:border-0"><span><strong>{a.title}</strong><span className="block text-xs text-muted-foreground">{a.n} nuits occupées</span></span><strong>{a.rate} %</strong></Link>)}</div></div>}
function Empty({show,text}:{show:boolean;text:string}){return show?<div className="rounded-sm border border-dashed border-border bg-card p-10 text-center text-sm text-muted-foreground">{text}</div>:null}
function ReservationPanel({event,onClose}:{event:ReservationCalendarEvent;onClose:()=>void}){return <div className="fixed inset-0 z-[120] bg-black/40" role="dialog" aria-modal="true" aria-label={`Détail ${event.reservationNumber}`}><button aria-label="Fermer le détail" className="absolute inset-0" onClick={onClose}/><aside className="absolute inset-y-0 right-0 w-full max-w-md overflow-auto bg-card p-6 shadow-2xl"><button aria-label="Fermer" onClick={onClose} className="float-right flex size-11 items-center justify-center"><X/></button><p className="text-xs font-bold uppercase text-gold">{event.reservationNumber}</p><h2 className="mt-2 font-display text-2xl font-semibold">{event.guestName}</h2>{event.isConflict&&<p className="mt-4 rounded-sm border border-red-500 bg-red-500/10 p-3 text-sm">⚠ Conflit de dates détecté. Examinez les réservations concernées.</p>}<dl className="mt-6 space-y-4 text-sm">{[['Appartement',event.apartmentTitle],['Arrivée',fr(event.checkIn)],['Départ',fr(event.checkOut)],['Nuits',event.nights],['Voyageurs',event.guests],['Statut',statusLabels[event.reservationStatus]],['Paiement',paymentLabels[event.paymentStatus]],['Total',money(event.totalAmount)],['Encaissé',money(event.paidAmount)],['Remboursé',money(event.refundedAmount)],['Solde',money(event.balanceDue)],['Téléphone',event.guestPhone??'Non renseigné']].map(([l,v])=><div key={l as string} className="flex justify-between gap-4 border-b border-border pb-3"><dt className="text-muted-foreground">{l}</dt><dd className="text-right font-medium">{v}</dd></div>)}</dl><div className="mt-6 grid gap-2"><Link href={`/dashboard/reservations/${event.id}`} className="tool">Voir la fiche</Link>{event.balanceDue!=null&&event.balanceDue>0&&<Link href={`/dashboard/payments/new?reservationId=${event.id}`} className="tool">Ajouter un paiement</Link>}{event.guestPhone&&<a href={`tel:${event.guestPhone}`} className="tool">Contacter</a>}</div></aside></div>}
