export type Status = "new" | "Nouveau" | "A qualifier" | "Contacte" | "Devis envoye" | "Confirme" | "Perdu" | "A relancer";

export type Lead = {
  id: string;
  name: string;
  phone: string;
  email?: string;
  request_type: string;
  district?: string;
  source: string;
  page_url?: string;
  related_type?: string;
  related_slug?: string;
  related_id?: string;
  status: Status;
  client_id?: string;
  owner_id?: string;
  converted_at?: string;
  message?: string;
  desired_date?: string;
  people_count?: number;
  estimated_budget?: number;
  metadata?: Record<string, unknown>;
  created_at: string;
};

export type Client = {
  id: string;
  full_name: string;
  phone: string;
  email?: string;
  nationality?: string;
  country?: string;
  city?: string;
  preferred_language?: string;
  client_type?: string;
  status?: string;
  tags?: string[];
  acquisition_source?: string;
  source?: string;
  notes?: string;
  preferences?: string | Record<string, unknown>;
  created_at: string;
  updated_at?: string;
};

export type Apartment = {
  id: string;
  company_id?: string;
  owner_id?: string | null;
  internal_name: string;
  public_name: string;
  internal_reference?: string;
  slug: string;
  district: string;
  city?: string;
  public_district?: string;
  address_private?: string;
  address_public_hint?: string;
  map_area?: string;
  property_type?: string;
  bedrooms: number;
  bathrooms?: number;
  beds?: number;
  capacity: number;
  floor?: string;
  has_elevator?: boolean;
  surface_area?: number;
  has_terrace?: boolean;
  has_pool?: boolean;
  has_parking?: boolean;
  price_from: number;
  price_per_night?: number;
  currency?: string;
  cleaning_fee?: number;
  deposit_amount?: number;
  minimum_nights?: number;
  commission_rate?: number;
  short_description?: string;
  detailed_description?: string;
  description?: string;
  highlights?: string[];
  amenities?: string[];
  house_rules?: string[];
  check_in_time?: string;
  check_out_time?: string;
  management_status?: string;
  public_status?: string;
  contract_status?: string;
  onboarding_status?: string;
  is_published: boolean;
  is_featured: boolean;
  published_at?: string;
  image_url?: string;
  image_alt_text?: string;
  access_instructions?: string;
  cleaning_instructions?: string;
  wifi_name?: string;
  wifi_password?: string;
  maintenance_notes?: string;
  internal_notes?: string;
  meta_title?: string;
  meta_description?: string;
  created_at?: string;
  updated_at?: string;
};

export type ApartmentImage = {
  id: string;
  company_id?: string;
  apartment_id: string;
  image_url?: string;
  image_path?: string;
  image_alt_text?: string;
  sort_order?: number;
  is_cover?: boolean;
  storage_bucket?: string;
  url?: string;
  alt_text?: string;
  display_order?: number;
  created_at?: string;
  updated_at?: string;
};

export type VehicleImage = {
  id: string;
  company_id?: string;
  vehicle_id: string;
  image_url?: string;
  image_path?: string;
  image_alt_text?: string;
  sort_order?: number;
  is_cover?: boolean;
  storage_bucket?: string;
  url?: string;
  alt_text?: string;
  display_order?: number;
  created_at?: string;
  updated_at?: string;
};

export type Vehicle = {
  id: string;
  company_id?: string;
  partner_id?: string | null;
  internal_name: string;
  public_name: string;
  title?: string;
  public_title?: string;
  internal_reference?: string;
  slug: string;
  brand?: string;
  model?: string;
  category?: string;
  vehicle_type?: string;
  capacity: number;
  luggage_capacity?: number;
  transmission?: string;
  fuel_type?: string;
  color?: string;
  registration?: string;
  plate_number?: string;
  ownership_type?: string;
  driver_required?: boolean;
  availability_status?: string;
  public_status?: string;
  management_status?: string;
  price_from: number;
  price_transfer?: number;
  price_half_day?: number;
  price_full_day?: number;
  price_per_km?: number;
  currency?: string;
  commission_rate?: number;
  commission?: number;
  partner_cost?: number;
  with_driver: boolean;
  is_published: boolean;
  is_featured?: boolean;
  short_description?: string;
  description?: string;
  public_description?: string;
  amenities?: string[];
  use_cases?: string[];
  internal_notes?: string;
  private_notes?: string;
  insurance_expiry_date?: string;
  technical_visit_expiry_date?: string;
  authorization_expiry_date?: string;
  image_url?: string;
  image_alt_text?: string;
  meta_title?: string;
  meta_description?: string;
  created_at?: string;
  updated_at?: string;
  vehicle_images?: VehicleImage[];
};

export type Reservation = {
  id: string;
  company_id?: string;
  reservation_number?: string;
  client_id?: string;
  apartment_id?: string;
  lead_id?: string;
  package_id?: string;
  check_in: string;
  check_out: string;
  nights: number;
  source?: string;
  external_reference?: string;
  external_url?: string;
  status: string;
  option_expires_at?: string;
  check_in_notes?: string;
  check_out_notes?: string;
  currency?: string;
  nightly_rate?: number;
  accommodation_subtotal?: number;
  cleaning_fee?: number;
  tourist_tax?: number;
  services_total?: number;
  discount_amount?: number;
  total_amount: number;
  deposit_amount: number;
  deposit_required?: number;
  remaining_amount: number;
  payment_status: string;
  arrival_time?: string;
  departure_time?: string;
  adults?: number;
  children?: number;
  infants?: number;
  total_guests?: number;
  people_count: number;
  guests_count?: number;
  guest_name?: string;
  guest_email?: string;
  guest_phone?: string;
  guest_country?: string;
  special_requests?: string;
  internal_notes?: string;
  cancellation_reason?: string;
  cancelled_at?: string;
  checked_in_at?: string;
  checked_out_at?: string;
  created_by?: string;
  updated_by?: string;
  created_at: string;
  updated_at: string;
  // Joined fields (not in DB)
  client_name?: string;
  apartment_name?: string;
};

export type ReservationEvent = {
  id: string;
  reservation_id: string;
  event_type: string;
  description: string;
  old_values?: Record<string, unknown>;
  new_values?: Record<string, unknown>;
  created_by?: string;
  created_at: string;
};

export type ReservationItem = {
  id: string;
  reservation_id: string;
  item_type: string;
  label: string;
  quantity: number;
  unit_price: number;
  total_amount: number;
  source_type?: string;
  source_id?: string;
  notes?: string;
  sort_order: number;
  created_at: string;
};

export type Trip = {
  id: string;
  company_id?: string;
  lead_id?: string;
  client_id?: string;
  vehicle_id?: string;
  partner_id?: string;
  package_id?: string;
  client_name?: string;
  vehicle_name?: string;
  title?: string;
  trip_type?: string;
  destination_label?: string;
  itinerary?: string;
  pickup_location?: string;
  dropoff_location?: string;
  trip_date: string;
  trip_time?: string;
  start_time?: string;
  end_time?: string;
  passengers_count?: number;
  departure: string;
  destination: string;
  sold_price: number;
  cost_price: number;
  amount?: number;
  cost_amount?: number;
  currency?: string;
  status: string;
  trip_status?: string;
  payment_status?: string;
  notes?: string;
  created_at?: string;
  updated_at?: string;
};

export type Transfer = {
  id: string;
  company_id?: string;
  lead_id?: string;
  client_id?: string;
  vehicle_id?: string;
  partner_id?: string;
  driver_name?: string;
  transfer_type: string;
  pickup_location?: string;
  dropoff_location?: string;
  pickup_date?: string;
  pickup_time?: string;
  passengers_count?: number;
  luggage_count?: number;
  flight_number?: string;
  amount: number;
  currency?: string;
  cost_amount: number;
  status: string;
  payment_status?: string;
  notes?: string;
  created_at?: string;
  updated_at?: string;
};

export type Payment = {
  id: string;
  company_id?: string;
  client_id?: string;
  lead_id?: string;
  reservation_id?: string;
  apartment_id?: string;
  owner_id?: string;
  trip_id?: string;
  vehicle_id?: string;
  partner_id?: string;
  transfer_id?: string;
  package_id?: string;
  client_name?: string;
  title?: string;
  description?: string;
  amount: number;
  currency?: string;
  payment_reference?: string;
  payment_type?: string;
  payment_part?: string;
  source?: string;
  stay_check_in?: string;
  stay_check_out?: string;
  guests_count?: number;
  paid_at: string;
  due_date?: string;
  payment_method: string;
  activity_type: string;
  status: string;
  receipt_url?: string;
  notes?: string;
  refunded_at?: string;
  created_at: string;
  updated_at?: string;
};

export type Expense = {
  id: string;
  company_id?: string;
  title?: string;
  description?: string;
  amount: number;
  currency?: string;
  expense_date: string;
  category: string;
  expense_status?: string;
  payment_method?: string;
  activity_type?: string;
  client_id?: string;
  lead_id?: string;
  reservation_id?: string;
  apartment_id?: string;
  vehicle_id?: string;
  trip_id?: string;
  transfer_id?: string;
  package_id?: string;
  partner_id?: string;
  supplier_name?: string;
  receipt_url?: string;
  notes?: string;
  created_at: string;
  updated_at?: string;
};

export type Partner = {
  id: string;
  company_id?: string;
  name: string;
  type: string;
  partner_type?: string;
  phone?: string;
  whatsapp?: string;
  email?: string;
  city?: string;
  address?: string;
  company_name?: string;
  ice?: string;
  tax_id?: string;
  contact_person?: string;
  preferred_contact_channel?: string;
  status?: string;
  service_categories?: string[];
  zones?: string[];
  languages?: string[];
  commission_rate?: number;
  default_cost_type?: string;
  payment_terms?: string;
  bank_name?: string;
  rib?: string;
  rating?: number;
  reliability_score?: number;
  notes?: string;
  internal_notes?: string;
  commission?: number;
  is_active: boolean;
  created_at?: string;
  updated_at?: string;
};

export type PackageItem = {
  id: string;
  package_id: string;
  item_type: string;
  item_id?: string;
  item_slug?: string;
  partner_id?: string | null;
  title: string;
  description?: string;
  quantity?: number;
  unit_label?: string;
  price_amount?: number;
  cost_amount?: number;
  sort_order?: number;
  is_optional?: boolean;
  created_at?: string;
  updated_at?: string;
};

export type Package = {
  id: string;
  company_id?: string;
  title: string;
  public_title?: string;
  slug: string;
  package_type?: string;
  short_description?: string;
  description?: string;
  destination?: string;
  duration_label?: string;
  capacity_min?: number;
  capacity_max?: number;
  price_from?: number;
  currency?: string;
  public_status?: string;
  is_featured?: boolean;
  image_url?: string;
  image_alt_text?: string;
  internal_notes?: string;
  created_at?: string;
  updated_at?: string;
  package_items?: PackageItem[];
};

export type Owner = {
  id: string;
  company_id?: string;
  full_name: string;
  phone: string;
  email?: string;
  city?: string;
  country?: string;
  preferred_contact_channel?: string;
  status: string;
  source?: string;
  lead_id?: string;
  notes?: string;
  tags?: string[];
  created_at: string;
  updated_at?: string;
};

export type MaintenanceTask = {
  id: string;
  company_id?: string;
  apartment_id?: string;
  owner_id?: string;
  title: string;
  description?: string;
  priority: string;
  status: string;
  category: string;
  estimated_cost?: number;
  actual_cost?: number;
  expense_id?: string;
  document_id?: string;
  due_date?: string;
  completed_at?: string;
  created_at: string;
  updated_at?: string;
};

export type OwnerStatement = {
  id: string;
  company_id?: string;
  owner_id: string;
  apartment_id?: string;
  period_start: string;
  period_end: string;
  gross_revenue: number;
  expenses_total: number;
  commission_amount: number;
  owner_net_amount: number;
  payout_status: string;
  statement_document_id?: string;
  notes?: string;
  created_at: string;
  updated_at?: string;
};

export type OwnerPayout = {
  id: string;
  company_id?: string;
  owner_id: string;
  apartment_id?: string;
  statement_id?: string;
  amount: number;
  currency: string;
  payout_method?: string;
  payout_status: string;
  paid_at?: string;
  notes?: string;
  created_at: string;
  updated_at?: string;
};

export type Document = {
  id: string;
  company_id?: string;
  title: string;
  description?: string;
  type: string;
  document_type?: string;
  category?: string;
  file_url?: string;
  file_path?: string;
  file_name?: string;
  file_size?: number;
  mime_type?: string;
  file_extension?: string;
  storage_bucket?: string;
  related_type?: string;
  related_id?: string;
  related_slug?: string;
  client_id?: string;
  owner_id?: string;
  apartment_id?: string;
  vehicle_id?: string;
  partner_id?: string;
  transfer_id?: string;
  trip_id?: string;
  package_id?: string;
  reservation_id?: string;
  payment_id?: string;
  expense_id?: string;
  expiry_date?: string;
  reminder_date?: string;
  doc_status?: string;
  is_private?: boolean;
  notes?: string;
  created_at: string;
  updated_at?: string;
};
